Repository AHNU-ATeam/MingPin-BackEnd, pull requests merged in 2024-10, with the labels that each got.

#85 作业功能3.1
  homework/src/main/java/com/chuanglian/mingpin/service/impl/HomeworkSubmissionServiceImpl.java
Labels: documentation

#87 学生功能3.4
  components/src/main/java/com/chuanglian/mingpin/entity/user/dto/UpdateStudentDTO.java
  homework/src/main/java/com/chuanglian/mingpin/controller/HomeworkAssignmentController.java
  homework/src/main/java/com/chuanglian/mingpin/service/impl/HomeworkAssignmentServiceImpl.java
  student-management/src/main/java/com/chuanglian/mingpin/controller/StudentController.java
  student-management/src/main/java/com/chuanglian/mingpin/service/StudentService.java
  student-management/src/main/java/com/chuanglian/mingpin/service/impl/StudentServiceImpl.java
Labels: documentation

#88 更新活动相册
  album/src/main/java/com/chuanglian/mingpin/controller/ClassAlbumController.java
  album/src/main/java/com/chuanglian/mingpin/pojo/ClassAlbumDTO.java
  album/src/main/java/com/chuanglian/mingpin/pojo/ClassAlbumInfoVO.java
  album/src/main/java/com/chuanglian/mingpin/pojo/ClassAlbumVO.java
  album/src/main/java/com/chuanglian/mingpin/pojo/ClassInfoVO.java
  album/src/main/java/com/chuanglian/mingpin/pojo/PublisherVO.java
  album/src/main/java/com/chuanglian/mingpin/service/ClassAlbumService.java
  album/src/main/java/com/chuanglian/mingpin/service/impl/ClassAlbumServiceImpl.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/impl/NotificationServiceImpl.java
  components/src/main/java/com/chuanglian/mingpin/entity/album/ClassAlbum.java
  core/src/main/resources/application.yml
Labels: bug, enhancement

#89 修复非匿名用户不能使用登录接口的问题
  core/src/main/java/com/chuanglian/mingpin/config/SecurityConfig.java
Labels: bug

#91 学生功能3.5
  student-management/src/main/java/com/chuanglian/mingpin/service/impl/StudentServiceImpl.java
Labels: bug, documentation

#92 展示教师信息新增返回信息以及注册操作中赋权限
  campus-management/src/main/java/com/chuanglian/mingpin/pojo/TeacherVoForShow.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/impl/TeacherServiceImpl.java
Labels: good first issue

#98 学生功能5.1
  components/src/main/java/com/chuanglian/mingpin/mapper/campus/ClassMgmtMapper.java
Labels: bug

#107 增加了OSS的部分功能
  core/src/main/java/com/chuanglian/mingpin/handler/GlobalExceptionHandler.java
  core/src/main/resources/application.yml
Labels: enhancement

#108 需要推送到服务器上，钱程要测试
  campus-management/src/main/java/com/chuanglian/mingpin/service/impl/TeacherServiceImpl.java
Labels: good first issue

#109 修改了Campus模块的VO类命名
  campus-management/src/main/java/com/chuanglian/mingpin/controller/TeacherController.java
  campus-management/src/main/java/com/chuanglian/mingpin/pojo/CampusTeacherVO.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/TeacherService.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/impl/TeacherServiceImpl.java
Labels: bug

#110 修复了登录时查找教师信息为null的问题
  login/src/main/java/com/chuanglian/mingpin/service/impl/LoginServiceImpl.java
Labels: bug
