Repository AHNU-ATeam/MingPin-BackEnd, pull requests merged in 2024-11, with the labels that each got.

#112 增加了修改密码的功能
  login/src/main/java/com/chuanglian/mingpin/controller/UserController.java
  login/src/main/java/com/chuanglian/mingpin/pojo/UserChangePasswordDTO.java
  login/src/main/java/com/chuanglian/mingpin/service/UserService.java
  login/src/main/java/com/chuanglian/mingpin/service/impl/LoginServiceImpl.java
  login/src/main/java/com/chuanglian/mingpin/service/impl/UserServiceImpl.java
Labels: enhancement

#111 Review.huang ln
  components/src/main/java/com/chuanglian/mingpin/entity/leave/dto/TeacherLeaveDTO.java
  components/src/main/java/com/chuanglian/mingpin/entity/user/vo/StudentVO.java
  student-management/src/main/java/com/chuanglian/mingpin/controller/StudentController.java
  student-management/src/main/java/com/chuanglian/mingpin/service/StudentService.java
  student-management/src/main/java/com/chuanglian/mingpin/service/impl/StudentServiceImpl.java
Labels: documentation

#114 增加了接收通知的功能
  campus-management/src/main/java/com/chuanglian/mingpin/controller/NotificationController.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/NotificationService.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/impl/NotificationServiceImpl.java
Labels: enhancement

#121 增加了获取打卡用户的功能
  attendance/src/main/java/com/chuanglian/mingpin/controller/AttendanceController.java
  attendance/src/main/java/com/chuanglian/mingpin/entity/vo/RequestDate.java
  attendance/src/main/java/com/chuanglian/mingpin/service/EmpAttendService.java
  attendance/src/main/java/com/chuanglian/mingpin/service/StuAttendService.java
  attendance/src/main/java/com/chuanglian/mingpin/service/impl/EmpAttendServiceImpl.java
  attendance/src/main/java/com/chuanglian/mingpin/service/impl/StuAttendServiceImpl.java
  campus-management/src/main/java/com/chuanglian/mingpin/controller/NotificationController.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/NotificationService.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/impl/NotificationServiceImpl.java
  core/pom.xml
  core/src/main/java/com/chuanglian/mingpin/config/MyBatisConfig.java
  login/src/main/java/com/chuanglian/mingpin/pojo/PrincipalVO.java
  login/src/main/java/com/chuanglian/mingpin/service/impl/LoginServiceImpl.java
  pom.xml
Labels: enhancement

#123 增加了教师登录的判断
  login/src/main/java/com/chuanglian/mingpin/service/impl/LoginServiceImpl.java
Labels: bug
