Repository AHNU-ATeam/MingPin-BackEnd, pull requests merged in 2024-09, with the labels that each got.

#27 与分支合并
  components/src/main/resources/mapper/CampMapper.xml
  components/src/main/resources/mapper/TeacherMapper.xml
  core/src/main/resources/application.yml
Labels: enhancement

#29 Review.huang ln
  core/pom.xml
  core/src/main/java/com/chuanglian/mingpin/MingPinApplication.java
  core/src/main/java/com/chuanglian/mingpin/config/SecurityConfig.java
  core/src/main/java/com/chuanglian/mingpin/config/WebConfig.java
  core/src/main/resources/application.yml
  core/src/main/resources/swagger-ui/favicon-16x16.png
  core/src/main/resources/swagger-ui/favicon-32x32.png
  core/src/main/resources/swagger-ui/index.css
  core/src/main/resources/swagger-ui/index.html
  core/src/main/resources/swagger-ui/oauth2-redirect.html
  core/src/main/resources/swagger-ui/swagger-initializer.js
  core/src/main/resources/swagger-ui/swagger-ui-bundle.js
  core/src/main/resources/swagger-ui/swagger-ui-bundle.js.map
  core/src/main/resources/swagger-ui/swagger-ui-es-bundle-core.js
  core/src/main/resources/swagger-ui/swagger-ui-es-bundle-core.js.map
  core/src/main/resources/swagger-ui/swagger-ui-es-bundle.js
  core/src/main/resources/swagger-ui/swagger-ui-es-bundle.js.map
  core/src/main/resources/swagger-ui/swagger-ui-standalone-preset.js
  core/src/main/resources/swagger-ui/swagger-ui-standalone-preset.js.map
  core/src/main/resources/swagger-ui/swagger-ui.css
  core/src/main/resources/swagger-ui/swagger-ui.css.map
  core/src/main/resources/swagger-ui/swagger-ui.js
  core/src/main/resources/swagger-ui/swagger-ui.js.map
  core/target/classes/application.yml
  core/target/classes/com/chuanglian/mingpin/MingPinApplication.class
  core/target/classes/com/chuanglian/mingpin/config/SecurityConfig.class
  pom.xml
  recipe/src/main/java/com/chuanglian/mingpin/controller/RecipeController.java
  student-management/src/main/java/com/chuanglian/mingpin/controller/StudentController.java
Labels: bug

#30 修复了不能启动的bug
  components/src/main/java/com/chuanglian/mingpin/entity/permission/UserRole.java
  components/src/main/java/com/chuanglian/mingpin/utils/JwtUtil.java
  components/src/main/resources/mapper/CampMapper.xml
  core/pom.xml
  core/src/main/java/com/chuanglian/mingpin/filter/JwtAuthenticationTokenFilter.java
  core/src/main/java/com/chuanglian/mingpin/service/impl/UserDetailsServiceImpl.java
  core/target/classes/application.yml
  core/target/classes/com/chuanglian/mingpin/filter/JwtAuthenticationTokenFilter.class
  homework/pom.xml
  homework/src/main/java/com/chuanglian/mingpin/App.java
  homework/src/main/java/com/chuanglian/mingpin/controller/HomeworkController.java
  homework/src/main/java/com/chuanglian/mingpin/service/HomeworkService.java
  homework/src/main/java/com/chuanglian/mingpin/service/impl/HomeworkServiceImpl.java
  pom.xml
Labels: bug

#31 删除过期无用的JsonFilter
  components/src/main/java/com/chuanglian/mingpin/entity/user/Student.java
Labels: bug

#32 修复Token时间不正常
  components/src/main/java/com/chuanglian/mingpin/utils/JwtUtil.java
Labels: bug

#33 推送0907
  campus-management/src/main/java/com/chuanglian/mingpin/controller/CampusController.java
  campus-management/src/main/java/com/chuanglian/mingpin/controller/TeacherController.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/CampService.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/TeacherService.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/impl/CampServiceImpl.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/impl/TeacherServiceImpl.java
  components/src/main/java/com/chuanglian/mingpin/entity/user/Teacher.java
  components/src/main/java/com/chuanglian/mingpin/entity/user/vo/TeacherVO.java
  components/src/main/java/com/chuanglian/mingpin/mapper/campus/CampMapper.java
  components/src/main/java/com/chuanglian/mingpin/mapper/user/TeacherMapper.java
  components/src/main/resources/mapper/TeacherMapper.xml
  components/target/classes/com/chuanglian/mingpin/pojo/Result.class
  core/pom.xml
  core/src/main/resources/application.yml
  core/target/classes/application.yml
Labels: enhancement

#34 食谱、学生删除和查询功能优化
  components/src/main/java/com/chuanglian/mingpin/entity/recipe/Recipe.java
  components/src/main/java/com/chuanglian/mingpin/entity/user/Student.java
  recipe/src/main/java/com/chuanglian/mingpin/controller/RecipeController.java
  recipe/src/main/java/com/chuanglian/mingpin/service/impl/RecipeServiceImpl.java
  student-management/src/main/java/com/chuanglian/mingpin/controller/StudentController.java
  student-management/src/main/java/com/chuanglian/mingpin/service/impl/StudentServiceImpl.java
Labels: bug

#36 删除delete请求
  core/pom.xml
  core/target/classes/com/chuanglian/mingpin/MingPinApplication.class
  core/target/classes/com/chuanglian/mingpin/config/RedisConfig.class
  core/target/classes/com/chuanglian/mingpin/config/SecurityConfig.class
  core/target/classes/com/chuanglian/mingpin/controller/TestController.class
  core/target/classes/com/chuanglian/mingpin/filter/JwtAuthenticationTokenFilter.class
  recipe/src/main/java/com/chuanglian/mingpin/controller/RecipeController.java
Labels: bug

#37 修改pom文件错误
  core/pom.xml
  core/target/classes/application.yml
Labels: bug

#40 食谱功能优化
  components/src/main/java/com/chuanglian/mingpin/entity/recipe/Recipe.java
  components/src/main/java/com/chuanglian/mingpin/mapper/recipe/RecipeMapper.java
  recipe/src/main/java/com/chuanglian/mingpin/controller/RecipeController.java
  recipe/src/main/java/com/chuanglian/mingpin/service/RecipeService.java
  recipe/src/main/java/com/chuanglian/mingpin/service/impl/RecipeServiceImpl.java
Labels: bug, enhancement

#42 Review.huang ln
  student-management/src/main/java/com/chuanglian/mingpin/controller/StudentController.java
Labels: documentation

#43 合并申请
  campus-management/src/main/java/com/chuanglian/mingpin/controller/CampusController.java
  campus-management/src/main/java/com/chuanglian/mingpin/controller/TeacherController.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/CampService.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/impl/CampServiceImpl.java
  components/src/main/java/com/chuanglian/mingpin/entity/campus/Campus.java
  components/src/main/java/com/chuanglian/mingpin/mapper/campus/CampMapper.java
  components/src/main/java/com/chuanglian/mingpin/mapper/user/TeacherMapper.java
  components/src/main/resources/mapper/CampMapper.xml
  core/pom.xml
Labels: bug

#44 实现了积分管理的所有功能
  components/src/main/java/com/chuanglian/mingpin/entity/point/Point.java
  components/src/main/java/com/chuanglian/mingpin/entity/point/PointRecords.java
  components/src/main/java/com/chuanglian/mingpin/entity/point/PointType.java
  components/src/main/java/com/chuanglian/mingpin/entity/point/vo/PointRecordsVo.java
  components/src/main/java/com/chuanglian/mingpin/entity/user/vo/StudentVo.java
  components/src/main/java/com/chuanglian/mingpin/mapper/point/PointMapper.java
  components/src/main/java/com/chuanglian/mingpin/mapper/point/PointRecordsMapper.java
  components/src/main/java/com/chuanglian/mingpin/mapper/point/PointTypeMapper.java
  components/src/main/java/com/chuanglian/mingpin/mapper/user/StudentMapper.java
  components/src/main/resources/mapper/PointMapper.xml
  components/src/main/resources/mapper/PointRecordsMapper.xml
  core/pom.xml
  point-management/.gitignore
  point-management/pom.xml
  point-management/src/main/java/com/chuanglian/mingpin/App.java
  point-management/src/main/java/com/chuanglian/mingpin/controller/PointController.java
  point-management/src/main/java/com/chuanglian/mingpin/controller/PointRecordsController.java
  point-management/src/main/java/com/chuanglian/mingpin/controller/PointTypeController.java
  point-management/src/main/java/com/chuanglian/mingpin/service/PointRecordsService.java
  point-management/src/main/java/com/chuanglian/mingpin/service/PointService.java
  point-management/src/main/java/com/chuanglian/mingpin/service/PointTypeService.java
  point-management/src/main/java/com/chuanglian/mingpin/service/impl/PointRecordsServiceImpl.java
  point-management/src/main/java/com/chuanglian/mingpin/service/impl/PointServiceImpl.java
  point-management/src/main/java/com/chuanglian/mingpin/service/impl/PointTypeServiceImpl.java
  point-management/src/test/java/com/chuanglian/mingpin/AppTest.java
  pom.xml
Labels: bug, enhancement

#48 食谱日期查找功能修改
  components/src/main/java/com/chuanglian/mingpin/entity/recipe/Recipe.java
Labels: bug

#51 食谱修改
  album/src/main/java/com/chuanglian/mingpin/controller/ClassAlbumController.java
  album/src/main/java/com/chuanglian/mingpin/pojo/ClassAlbumDTO.java
  album/src/main/java/com/chuanglian/mingpin/pojo/ImageVO.java
  album/src/main/java/com/chuanglian/mingpin/pojo/VideoVO.java
  album/src/main/java/com/chuanglian/mingpin/service/ClassAlbumService.java
  album/src/main/java/com/chuanglian/mingpin/service/impl/ClassAlbumServiceImpl.java
  components/src/main/java/com/chuanglian/mingpin/entity/album/ClassAlbum.java
  components/src/main/java/com/chuanglian/mingpin/entity/album/Image.java
  components/src/main/java/com/chuanglian/mingpin/entity/album/Video.java
  components/src/main/java/com/chuanglian/mingpin/mapper/album/ClassAlbumMapper.java
  components/src/main/java/com/chuanglian/mingpin/mapper/album/ImagesMapper.java
  components/src/main/java/com/chuanglian/mingpin/mapper/album/VideoMapper.java
  recipe/src/main/java/com/chuanglian/mingpin/service/impl/RecipeServiceImpl.java
Labels: bug

#52 Review.yao jb
  campus-management/src/main/java/com/chuanglian/mingpin/controller/TeacherController.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/impl/TeacherServiceImpl.java
  components/src/main/java/com/chuanglian/mingpin/entity/user/Teacher.java
  components/src/main/java/com/chuanglian/mingpin/entity/user/vo/TeacherVO.java
  components/src/main/java/com/chuanglian/mingpin/mapper/user/TeacherMapper.java
Labels: invalid, question

#55 增加代码审查配置文件
  .github/workflows/build.yml
Labels: bug

#56 Create sonarqube.yml
  .github/workflows/sonarqube.yml
Labels: bug

#61 修改教师管理
  album/src/main/java/com/chuanglian/mingpin/controller/ClassAlbumController.java
  album/src/main/java/com/chuanglian/mingpin/pojo/ClassAlbumDTO.java
  album/src/main/java/com/chuanglian/mingpin/pojo/ClassAlbumImageVO.java
  album/src/main/java/com/chuanglian/mingpin/pojo/ClassAlbumVO.java
  album/src/main/java/com/chuanglian/mingpin/pojo/ClassAlbumVideoVO.java
  album/src/main/java/com/chuanglian/mingpin/service/ClassAlbumService.java
  album/src/main/java/com/chuanglian/mingpin/service/impl/ClassAlbumServiceImpl.java
  campus-management/src/main/java/com/chuanglian/mingpin/controller/TeacherController.java
  campus-management/src/main/java/com/chuanglian/mingpin/pojo/ImageVO.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/impl/TeacherServiceImpl.java
  components/src/main/java/com/chuanglian/mingpin/entity/user/Teacher.java
  core/pom.xml
Labels: bug

#62 处理通知模块的Bug
  album/pom.xml
  attendance/pom.xml
  campus-management/pom.xml
  campus-management/src/main/java/com/chuanglian/mingpin/controller/NotificationController.java
  campus-management/src/main/java/com/chuanglian/mingpin/pojo/FileVO.java
  campus-management/src/main/java/com/chuanglian/mingpin/pojo/NotificationVO.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/impl/NotificationServiceImpl.java
  class-management/pom.xml
  components/pom.xml
  components/src/main/java/com/chuanglian/mingpin/annotation/ValidFile.java
  homework/pom.xml
  login/pom.xml
  point-management/pom.xml
  pom.xml
  recipe/pom.xml
  student-management/pom.xml
Labels: bug

#63 完成活动相册的基本功能
  .github/workflows/build.yml
  album/src/main/java/com/chuanglian/mingpin/controller/ClassAlbumController.java
  album/src/main/java/com/chuanglian/mingpin/pojo/ClassAlbumImageVO.java
  album/src/main/java/com/chuanglian/mingpin/pojo/ClassAlbumVO.java
  album/src/main/java/com/chuanglian/mingpin/pojo/ClassAlbumVideoVO.java
  album/src/main/java/com/chuanglian/mingpin/service/ClassAlbumService.java
  album/src/main/java/com/chuanglian/mingpin/service/impl/ClassAlbumServiceImpl.java
  campus-management/src/main/java/com/chuanglian/mingpin/pojo/NotificationVO.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/impl/NotificationServiceImpl.java
Labels: bug

#64 Review.huang ln
  components/pom.xml
  components/src/main/java/com/chuanglian/mingpin/entity/homework/HomeworkAssignment.java
  components/src/main/java/com/chuanglian/mingpin/entity/homework/HomeworkSubmission.java
  components/src/main/java/com/chuanglian/mingpin/entity/homework/vo/CorrectSubmissionVo.java
  components/src/main/java/com/chuanglian/mingpin/mapper/homework/HomeworkAssignmentMapper.java
  components/src/main/java/com/chuanglian/mingpin/mapper/homework/HomeworkSubmissionMapper.java
  components/src/main/java/com/chuanglian/mingpin/mapper/recipe/RecipeMapper.java
  components/src/main/java/com/chuanglian/mingpin/mapper/user/StudentMapper.java
  core/pom.xml
  homework/pom.xml
  homework/src/main/java/com/chuanglian/mingpin/controller/HomeworkAssignmentController.java
  homework/src/main/java/com/chuanglian/mingpin/controller/HomeworkController.java
  homework/src/main/java/com/chuanglian/mingpin/controller/HomeworkSubmissionController.java
  homework/src/main/java/com/chuanglian/mingpin/service/HomeworkAssignmentService.java
  homework/src/main/java/com/chuanglian/mingpin/service/HomeworkService.java
  homework/src/main/java/com/chuanglian/mingpin/service/HomeworkSubmissionService.java
  homework/src/main/java/com/chuanglian/mingpin/service/impl/HomeworkAssignmentServiceImpl.java
  homework/src/main/java/com/chuanglian/mingpin/service/impl/HomeworkServiceImpl.java
  homework/src/main/java/com/chuanglian/mingpin/service/impl/HomeworkSubmissionServiceImpl.java
  recipe/src/main/java/com/chuanglian/mingpin/controller/RecipeController.java
  recipe/src/main/java/com/chuanglian/mingpin/service/impl/RecipeServiceImpl.java
  student-management/src/main/java/com/chuanglian/mingpin/controller/StudentController.java
  student-management/src/main/java/com/chuanglian/mingpin/service/StudentService.java
  student-management/src/main/java/com/chuanglian/mingpin/service/impl/StudentServiceImpl.java
Labels: documentation

#65 Review.yao jb
  campus-management/src/main/java/com/chuanglian/mingpin/controller/CampusController.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/CampService.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/impl/CampServiceImpl.java
  components/src/main/java/com/chuanglian/mingpin/entity/campus/Campus.java
  components/src/main/java/com/chuanglian/mingpin/mapper/campus/CampMapper.java
Labels: documentation

#66 Review.huang ln
  components/src/main/java/com/chuanglian/mingpin/entity/homework/vo/SubmissionDetailVo.java
  homework/src/main/java/com/chuanglian/mingpin/controller/HomeworkSubmissionController.java
  homework/src/main/java/com/chuanglian/mingpin/service/HomeworkSubmissionService.java
  homework/src/main/java/com/chuanglian/mingpin/service/impl/HomeworkSubmissionServiceImpl.java
Labels: documentation

#67 Revert "Review.huang ln"
  components/src/main/java/com/chuanglian/mingpin/entity/homework/vo/SubmissionDetailVo.java
  homework/src/main/java/com/chuanglian/mingpin/controller/HomeworkSubmissionController.java
  homework/src/main/java/com/chuanglian/mingpin/service/HomeworkSubmissionService.java
  homework/src/main/java/com/chuanglian/mingpin/service/impl/HomeworkSubmissionServiceImpl.java
Labels: bug

#69 Revert "Review.huang ln"
  components/pom.xml
  components/src/main/java/com/chuanglian/mingpin/entity/homework/HomeworkAssignment.java
  components/src/main/java/com/chuanglian/mingpin/entity/homework/HomeworkSubmission.java
  components/src/main/java/com/chuanglian/mingpin/entity/homework/vo/CorrectSubmissionVo.java
  components/src/main/java/com/chuanglian/mingpin/mapper/homework/HomeworkAssignmentMapper.java
  components/src/main/java/com/chuanglian/mingpin/mapper/homework/HomeworkSubmissionMapper.java
  components/src/main/java/com/chuanglian/mingpin/mapper/recipe/RecipeMapper.java
  components/src/main/java/com/chuanglian/mingpin/mapper/user/StudentMapper.java
  core/pom.xml
  homework/pom.xml
  homework/src/main/java/com/chuanglian/mingpin/controller/HomeworkAssignmentController.java
  homework/src/main/java/com/chuanglian/mingpin/controller/HomeworkController.java
  homework/src/main/java/com/chuanglian/mingpin/controller/HomeworkSubmissionController.java
  homework/src/main/java/com/chuanglian/mingpin/service/HomeworkAssignmentService.java
  homework/src/main/java/com/chuanglian/mingpin/service/HomeworkService.java
  homework/src/main/java/com/chuanglian/mingpin/service/HomeworkSubmissionService.java
  homework/src/main/java/com/chuanglian/mingpin/service/impl/HomeworkAssignmentServiceImpl.java
  homework/src/main/java/com/chuanglian/mingpin/service/impl/HomeworkServiceImpl.java
  homework/src/main/java/com/chuanglian/mingpin/service/impl/HomeworkSubmissionServiceImpl.java
  recipe/src/main/java/com/chuanglian/mingpin/controller/RecipeController.java
  recipe/src/main/java/com/chuanglian/mingpin/service/impl/RecipeServiceImpl.java
  student-management/src/main/java/com/chuanglian/mingpin/controller/StudentController.java
  student-management/src/main/java/com/chuanglian/mingpin/service/StudentService.java
  student-management/src/main/java/com/chuanglian/mingpin/service/impl/StudentServiceImpl.java
Labels: bug

#70 修改部分Maven坐标
  components/pom.xml
  point-management/pom.xml
  pom.xml
Labels: bug

#71 完善登录和消息模块
  album/src/main/java/com/chuanglian/mingpin/controller/ClassAlbumController.java
  campus-management/src/main/java/com/chuanglian/mingpin/controller/NotificationController.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/NotificationService.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/impl/NotificationServiceImpl.java
  components/src/main/java/com/chuanglian/mingpin/annotation/ValidFile.java
  components/src/main/java/com/chuanglian/mingpin/entity/campus/Campus.java
  components/src/main/java/com/chuanglian/mingpin/entity/permission/Role.java
  components/src/main/java/com/chuanglian/mingpin/entity/permission/UserRole.java
  components/src/main/java/com/chuanglian/mingpin/entity/user/User.java
  components/src/main/java/com/chuanglian/mingpin/filter/FileValidator.java
  components/src/main/java/com/chuanglian/mingpin/mapper/campus/CampMapper.java
  components/src/main/java/com/chuanglian/mingpin/mapper/permission/RoleMapper.java
  components/src/main/java/com/chuanglian/mingpin/mapper/point/PointMapper.java
  components/src/main/java/com/chuanglian/mingpin/mapper/user/PrincipalMapper.java
  components/src/main/java/com/chuanglian/mingpin/utils/RoleEnum.java
  login/src/main/java/com/chuanglian/mingpin/controller/RegisterController.java
  login/src/main/java/com/chuanglian/mingpin/pojo/UserVO.java
  login/src/main/java/com/chuanglian/mingpin/service/RegisterService.java
  login/src/main/java/com/chuanglian/mingpin/service/impl/LoginServiceImpl.java
  login/src/main/java/com/chuanglian/mingpin/service/impl/RegisterServiceImpl.java
  pom.xml
Labels: bug

#72 修正增加教师
  campus-management/src/main/java/com/chuanglian/mingpin/controller/TeacherController.java
  campus-management/src/main/java/com/chuanglian/mingpin/pojo/TeacherVO.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/TeacherService.java
  campus-management/src/main/java/com/chuanglian/mingpin/service/impl/TeacherServiceImpl.java
  components/src/main/java/com/chuanglian/mingpin/entity/user/Teacher.java
  components/src/main/java/com/chuanglian/mingpin/entity/user/User.java
  components/src/main/java/com/chuanglian/mingpin/entity/user/vo/TeacherVO.java
  components/src/main/java/com/chuanglian/mingpin/mapper/user/TeacherMapper.java
  login/src/main/java/com/chuanglian/mingpin/service/impl/RegisterServiceImpl.java
Labels: documentation

#75 学生功能2.3
  student-management/src/main/java/com/chuanglian/mingpin/service/impl/StudentServiceImpl.java
Labels: documentation

#79 学生功能3.1
  student-management/src/main/java/com/chuanglian/mingpin/service/impl/StudentServiceImpl.java
Labels: documentation

#81 Review.huang ln
  components/src/main/java/com/chuanglian/mingpin/entity/homework/DTO/AssignmentDTO.java
  components/src/main/java/com/chuanglian/mingpin/entity/homework/DTO/SubmissionDTO.java
  components/src/main/java/com/chuanglian/mingpin/entity/homework/DTO/UpdateAssignmentDTO.java
  components/src/main/java/com/chuanglian/mingpin/entity/homework/DTO/UpdateSubmissionDTO.java
  components/src/main/java/com/chuanglian/mingpin/entity/homework/HomeworkSubmission.java
  components/src/main/java/com/chuanglian/mingpin/entity/homework/VO/AssignmentVO.java
  components/src/main/java/com/chuanglian/mingpin/entity/homework/VO/SubmissionVO.java
  homework/src/main/java/com/chuanglian/mingpin/controller/HomeworkAssignmentController.java
  homework/src/main/java/com/chuanglian/mingpin/controller/HomeworkSubmissionController.java
  homework/src/main/java/com/chuanglian/mingpin/service/HomeworkAssignmentService.java
  homework/src/main/java/com/chuanglian/mingpin/service/HomeworkSubmissionService.java
  homework/src/main/java/com/chuanglian/mingpin/service/impl/HomeworkAssignmentServiceImpl.java
  homework/src/main/java/com/chuanglian/mingpin/service/impl/HomeworkSubmissionServiceImpl.java
  student-management/src/main/java/com/chuanglian/mingpin/service/impl/StudentServiceImpl.java
Labels: documentation
